#! /bin/sh
#

### BEGIN INIT INFO
# Provides:          tcos-multi
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
set -u -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=tcos-multi
DESC="Compatibility script to launch legacy (=TCOS<2.0) tcos boot scripts on run level 2345"

SCRIPT_DIRS_OPT=/opt/*/tcos/rc2345.d

# Get LSB functions
. /lib/lsb/init-functions 
. /etc/default/rcS


runparts_opt() {

	ERRORLEVEL=0
	for dir in $SCRIPT_DIRS_OPT; do
		if [ -d "$dir" ]; then
			run-parts --lsbsysinit --new-session --arg=start "$dir"
			if [ $? -ne 0 ]; then
				ERRORLEVEL=65
			fi
		fi
	done
	return $ERRORLEVEL
}

case "$1" in
  start)
	log_begin_msg "Building TCOS opt config..."
	if runparts_opt; then
		log_end_msg 0
	else
		log_end_msg $?
	fi
	;;
     
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start}" >&2
	exit 1
	;;
esac

exit 0
