#!/usr/bin/env python

import base64
#import tcos
import ldapurl
import pytcos.tcos as tcos
l = tcos.Ldap() 
s = tcos.System()
u = tcos.Util() 

ldap_url = s.getLdapUrl()

filename = "/etc/pam_ldap.conf"
pam_filter = "objectclass=person"
pam_login_attribute = "cn"

pam_ldap_url = l.getPamLdapUrl(ldap_url)
pam_lurl = ldapurl.LDAPUrl(pam_ldap_url)

try:
	password = base64.b64decode(pam_lurl.cred)
except TypeError:
	password = pam_lurl.cred

server_type = l.guessServerType(pam_ldap_url)
if server_type == l.DirectoryType.ADS:
	pam_filter = "&(objectclass=person)(!(objectclass=computer))"
	pam_login_attribute = "sAMAccountName"
elif server_type == l.DirectoryType.OPENLDAP:
	pam_filter = "objectclass=posixAccount"
	pam_login_attribute = "uid"

entry_dict = {"host" : pam_lurl.hostport,
              "base" : pam_lurl.dn,
              "pam_filter" : pam_filter,
              "pam_login_attribute" : pam_login_attribute}

if pam_lurl.who:
	entry_dict["binddn"] = pam_lurl.who
if password:
	entry_dict["bindpw"] = password

#pam_sasl_mechs = l.getPamSaslMechanisms(pam_ldap_url)
#for mech in pam_sasl_mechs:
#	if mech == "DIGEST-MD5":
#		entry_dict["pam_sasl_mech"] = mech

u.writeDictionaryToFile(entry_dict, filename, " ", "")

mac = s.getMac()
client_dn = l.getClientDn(mac, ldap_url)
devices_dn = l.getDevicesDn(client_dn, ldap_url)
user_dn = l.getUserDn('tcos', ldap_url)
apps_dn_list = l.getAppsDn(client_dn, user_dn, ldap_url)

def write_lightdmconf(filename="/etc/lightdm/lightdm.conf"):
 
    types = map(lambda d: l.getGroupOfUniqueNamesInfo(d, ldap_url)["schema"], \
            devices_dn+apps_dn_list)
    if "autologin" in types:
       content="""\
[LightDM]

[SeatDefaults]
greeter-session=lightdm-greeter
greeter-hide-users=true
display-setup-script=/usr/local/bin/tcos-xrandr 
session-wrapper=/etc/X11/Xsession
session-setup-script=/usr/local/bin/tcos-postlogin 
autologin-user=tcos
autologin-user-timeout=0
"""
    else:
        content="""\
[LightDM]

[SeatDefaults]
greeter-session=lightdm-greeter
greeter-hide-users=true
display-setup-script=/usr/local/bin/tcos-xrandr 
session-wrapper=/etc/X11/Xsession
session-setup-script=/usr/local/bin/tcos-postlogin 
autologin-user=
autologin-user-timeout=0
"""
##X-remote-tcp
####################################################
#    if "desktop" in types:
#        for app_dn in apps_dn_list:
#            if l.getGroupOfUniqueNamesInfo(app_dn, ldap_url)['schema'] == 'desktop':
#                if l.getNismapentry(app_dn, ldap_url)['lightdmparser.allow-tcp'] == 'true':
#                    content+="xserver-allow-tcp=true\n"

    with open(filename, 'w') as fobj:
        fobj.write(content)

write_lightdmconf()
