'\" t
.\"     Title: xfreerdp
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2015-11-12
.\"    Manual: xfreerdp
.\"    Source: freerdp
.\"  Language: English
.\"
.TH "XFREERDP" "1" "2015\-11\-12" "freerdp" "xfreerdp"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xfreerdp \- FreeRDP X11 client
.SH "SYNOPSIS"
.PP

\fBxfreerdp\fR
[file] [options] [/v:server[:port]]
.SH "DESCRIPTION"
.PP

\fBxfreerdp\fR
is an X11 Remote Desktop Protocol (RDP) client which is part of the FreeRDP project\&. An RDP server is built\-in to many editions of Windows\&. Alternative servers included xrdp and VRDP (VirtualBox)\&.
.SH "OPTIONS"
.PP
\fB/v\fR \fI<server>[:port]\fR
.RS 4
<server>[:port]
.RE
.PP
\fB/port\fR \fI<number>\fR
.RS 4
<number>
.RE
.PP
\fB/w\fR \fI<width>\fR
.RS 4
<width>
.RE
.PP
\fB/h\fR \fI<height>\fR
.RS 4
<height>
.RE
.PP
\fB/size\fR \fI<width>x<height> or <percent>%\fR
.RS 4
<width>x<height> or <percent>%
.RE
.PP
\fB/f\fR
.RS 4
(null)
.RE
.PP
\fB/bpp\fR \fI<depth>\fR
.RS 4
<depth>
.RE
.PP
\fB/kbd\fR \fI0x<layout id> or <layout name>\fR
.RS 4
0x<layout id> or <layout name>
.RE
.PP
\fB/kbd\-list\fR
.RS 4
(null)
.RE
.PP
\fB/kbd\-type\fR \fI<type id>\fR
.RS 4
<type id>
.RE
.PP
\fB/kbd\-subtype\fR \fI<subtype id>\fR
.RS 4
<subtype id>
.RE
.PP
\fB/kbd\-fn\-key\fR \fI<function key count>\fR
.RS 4
<function key count>
.RE
.PP
\fB/admin\fR
.RS 4
(null)
.RE
.PP
\fB/restricted\-admin\fR
.RS 4
(null)
.RE
.PP
\fB/pth\fR \fI<password hash>\fR
.RS 4
<password hash>
.RE
.PP
\fB/client\-hostname\fR \fI<name>\fR
.RS 4
<name>
.RE
.PP
\fB/multimon\fR
.RS 4
(null)
.RE
.PP
\fB/span\fR
.RS 4
(null)
.RE
.PP
\fB/workarea\fR
.RS 4
(null)
.RE
.PP
\fB/monitors\fR \fI<0,1,2\&.\&.\&.>\fR
.RS 4
<0,1,2\&.\&.\&.>
.RE
.PP
\fB/monitor\-list\fR
.RS 4
(null)
.RE
.PP
\fB/t\fR \fI<title>\fR
.RS 4
<title>
.RE
.PP
\fB/decorations\fR
.RS 4
(null)
.RE
.PP
\fB/smart\-sizing\fR
.RS 4
<width>x<height>
.RE
.PP
\fB/a\fR \fI(null)\fR
.RS 4
(null)
.RE
.PP
\fB/vc\fR \fI(null)\fR
.RS 4
(null)
.RE
.PP
\fB/dvc\fR \fI(null)\fR
.RS 4
(null)
.RE
.PP
\fB/u\fR \fI[<domain>\e]<user> or <user>[@<domain>]\fR
.RS 4
[<domain>\e]<user> or <user>[@<domain>]
.RE
.PP
\fB/p\fR \fI<password>\fR
.RS 4
<password>
.RE
.PP
\fB/d\fR \fI<domain>\fR
.RS 4
<domain>
.RE
.PP
\fB/g\fR
.RS 4
<gateway>[:port]
.RE
.PP
\fB/gu\fR \fI[<domain>\e]<user> or <user>[@<domain>]\fR
.RS 4
[<domain>\e]<user> or <user>[@<domain>]
.RE
.PP
\fB/gp\fR \fI<password>\fR
.RS 4
<password>
.RE
.PP
\fB/gd\fR \fI<domain>\fR
.RS 4
<domain>
.RE
.PP
\fB/gt\fR \fI<rpc|http|auto>\fR
.RS 4
<rpc|http|auto>
.RE
.PP
\fB/gateway\-usage\-method\fR \fI<direct|detect>\fR
.RS 4
<direct|detect>
.RE
.PP
\fB/load\-balance\-info\fR \fI<info string>\fR
.RS 4
<info string>
.RE
.PP
\fB/app\fR \fI<executable path> or <||alias>\fR
.RS 4
<executable path> or <||alias>
.RE
.PP
\fB/app\-name\fR \fI<app name>\fR
.RS 4
<app name>
.RE
.PP
\fB/app\-icon\fR \fI<icon path>\fR
.RS 4
<icon path>
.RE
.PP
\fB/app\-cmd\fR \fI<parameters>\fR
.RS 4
<parameters>
.RE
.PP
\fB/app\-file\fR \fI<file name>\fR
.RS 4
<file name>
.RE
.PP
\fB/app\-guid\fR \fI<app guid>\fR
.RS 4
<app guid>
.RE
.PP
\fB/compression\fR
.RS 4
(null)
.RE
.PP
\fB/compression\-level\fR \fI<level>\fR
.RS 4
<level>
.RE
.PP
\fB/shell\fR \fI(null)\fR
.RS 4
(null)
.RE
.PP
\fB/shell\-dir\fR \fI(null)\fR
.RS 4
(null)
.RE
.PP
\fB/sound\fR
.RS 4
[sys][dev][format][rate][channel][latency][quality]
.RE
.PP
\fB/microphone\fR
.RS 4
[sys][dev][format][rate][channel]
.RE
.PP
\fB/audio\-mode\fR \fI(null)\fR
.RS 4
(null)
.RE
.PP
\fB/multimedia\fR
.RS 4
[sys][dev][decoder]
.RE
.PP
\fB/network\fR \fI(null)\fR
.RS 4
(null)
.RE
.PP
\fB/drive\fR \fI(null)\fR
.RS 4
(null)
.RE
.PP
\fB/drives\fR
.RS 4
(null)
.RE
.PP
\fB/home\-drive\fR
.RS 4
(null)
.RE
.PP
\fB/clipboard\fR
.RS 4
(null)
.RE
.PP
\fB/serial\fR
.RS 4
(null)
.RE
.PP
\fB/parallel\fR
.RS 4
(null)
.RE
.PP
\fB/smartcard\fR
.RS 4
(null)
.RE
.PP
\fB/printer\fR
.RS 4
(null)
.RE
.PP
\fB/usb\fR \fI[dbg][dev][id|addr][auto]\fR
.RS 4
[dbg][dev][id|addr][auto]
.RE
.PP
\fB/multitouch\fR
.RS 4
(null)
.RE
.PP
\fB/gestures\fR
.RS 4
(null)
.RE
.PP
\fB/echo\fR
.RS 4
(null)
.RE
.PP
\fB/disp\fR
.RS 4
(null)
.RE
.PP
\fB/fonts\fR
.RS 4
(null)
.RE
.PP
\fB/aero\fR
.RS 4
(null)
.RE
.PP
\fB/window\-drag\fR
.RS 4
(null)
.RE
.PP
\fB/menu\-anims\fR
.RS 4
(null)
.RE
.PP
\fB/themes\fR
.RS 4
(null)
.RE
.PP
\fB/wallpaper\fR
.RS 4
(null)
.RE
.PP
\fB/gdi\fR \fI<sw|hw>\fR
.RS 4
<sw|hw>
.RE
.PP
\fB/gfx\fR
.RS 4
(null)
.RE
.PP
\fB/gfx\-thin\-client\fR
.RS 4
(null)
.RE
.PP
\fB/gfx\-small\-cache\fR
.RS 4
(null)
.RE
.PP
\fB/gfx\-progressive\fR
.RS 4
(null)
.RE
.PP
\fB/gfx\-h264\fR
.RS 4
(null)
.RE
.PP
\fB/rfx\fR
.RS 4
(null)
.RE
.PP
\fB/rfx\-mode\fR \fI<image|video>\fR
.RS 4
<image|video>
.RE
.PP
\fB/frame\-ack\fR \fI<number>\fR
.RS 4
<number>
.RE
.PP
\fB/nsc\fR
.RS 4
(null)
.RE
.PP
\fB/jpeg\fR
.RS 4
(null)
.RE
.PP
\fB/jpeg\-quality\fR \fI<percentage>\fR
.RS 4
<percentage>
.RE
.PP
\fB/nego\fR
.RS 4
(null)
.RE
.PP
\fB/sec\fR \fI<rdp|tls|nla|ext>\fR
.RS 4
<rdp|tls|nla|ext>
.RE
.PP
\fB/sec\-rdp\fR
.RS 4
(null)
.RE
.PP
\fB/sec\-tls\fR
.RS 4
(null)
.RE
.PP
\fB/sec\-nla\fR
.RS 4
(null)
.RE
.PP
\fB/sec\-ext\fR
.RS 4
(null)
.RE
.PP
\fB/tls\-ciphers\fR \fI<netmon|ma|ciphers>\fR
.RS 4
<netmon|ma|ciphers>
.RE
.PP
\fB/cert\-name\fR \fI<name>\fR
.RS 4
<name>
.RE
.PP
\fB/cert\-ignore\fR
.RS 4
(null)
.RE
.PP
\fB/pcb\fR \fI<blob>\fR
.RS 4
<blob>
.RE
.PP
\fB/pcid\fR \fI<id>\fR
.RS 4
<id>
.RE
.PP
\fB/spn\-class\fR \fI<service class>\fR
.RS 4
<service class>
.RE
.PP
\fB/credentials\-delegation\fR
.RS 4
(null)
.RE
.PP
\fB/vmconnect\fR
.RS 4
<vmid>
.RE
.PP
\fB/authentication\fR
.RS 4
(null)
.RE
.PP
\fB/encryption\fR
.RS 4
(null)
.RE
.PP
\fB/grab\-keyboard\fR
.RS 4
(null)
.RE
.PP
\fB/toggle\-fullscreen\fR
.RS 4
(null)
.RE
.PP
\fB/mouse\-motion\fR
.RS 4
(null)
.RE
.PP
\fB/parent\-window\fR \fI<window id>\fR
.RS 4
<window id>
.RE
.PP
\fB/bitmap\-cache\fR
.RS 4
(null)
.RE
.PP
\fB/offscreen\-cache\fR
.RS 4
(null)
.RE
.PP
\fB/glyph\-cache\fR
.RS 4
(null)
.RE
.PP
\fB/codec\-cache\fR \fI<rfx|nsc|jpeg>\fR
.RS 4
<rfx|nsc|jpeg>
.RE
.PP
\fB/fast\-path\fR
.RS 4
(null)
.RE
.PP
\fB/max\-fast\-path\-size\fR
.RS 4
<size>
.RE
.PP
\fB/async\-input\fR
.RS 4
(null)
.RE
.PP
\fB/async\-update\fR
.RS 4
(null)
.RE
.PP
\fB/async\-transport\fR
.RS 4
(null)
.RE
.PP
\fB/async\-channels\fR
.RS 4
(null)
.RE
.PP
\fB/wm\-class\fR \fI<class name>\fR
.RS 4
<class name>
.RE
.PP
\fB/version\fR
.RS 4
(null)
.RE
.PP
\fB/help\fR
.RS 4
(null)
.RE
.PP
\fB/play\-rfx\fR \fI<pcap file>\fR
.RS 4
<pcap file>
.RE
.PP
\fB/auth\-only\fR
.RS 4
(null)
.RE
.PP
\fB/auto\-reconnect\fR
.RS 4
(null)
.RE
.PP
\fB/reconnect\-cookie\fR \fI<base64 cookie>\fR
.RS 4
<base64 cookie>
.RE
.PP
\fB/print\-reconnect\-cookie\fR
.RS 4
(null)
.RE
.PP
\fB/heartbeat\fR
.RS 4
(null)
.RE
.PP
\fB/multitransport\fR
.RS 4
(null)
.RE
.PP
\fB/assistance\fR \fI<password>\fR
.RS 4
<password>
.RE
.PP
\fB/encryption\-methods\fR \fI<40,56,128,FIPS>\fR
.RS 4
<40,56,128,FIPS>
.RE
.PP
\fB/from\-stdin\fR
.RS 4
(null)
.RE
.SH "EXAMPLES"
.PP
\fBxfreerdp connection\&.rdp /p:Pwd123! /f\fR
.RS 4
Connect in fullscreen mode using a stored configuration
\fIconnection\&.rdp\fR
and the password
\fIPwd123!\fR
.RE
.PP
\fBxfreerdp /u:CONTOSO\e\eJohnDoe /p:Pwd123! /v:rdp\&.contoso\&.com\fR
.RS 4
Connect to host
\fIrdp\&.contoso\&.com\fR
with user
\fICONTOSO\e\eJohnDoe\fR
and password
\fIPwd123!\fR
.RE
.PP
\fBxfreerdp /u:JohnDoe /p:Pwd123! /w:1366 /h:768 /v:192\&.168\&.1\&.100:4489\fR
.RS 4
Connect to host
\fI192\&.168\&.1\&.100\fR
on port
\fI4489\fR
with user
\fIJohnDoe\fR, password
\fIPwd123!\fR\&. The screen width is set to
\fI1366\fR
and the height to
\fI768\fR
.RE
.PP
\fBxfreerdp /u:JohnDoe /p:Pwd123! /vmconnect:C824F53E\-95D2\-46C6\-9A18\-23A5BB403532 /v:192\&.168\&. 1\&.100\fR
.RS 4
Establish a connection to host
\fI192\&.168\&.1\&.100\fR
with user
\fIJohnDoe\fR, password
\fIPwd123!\fR
and connect to Hyper\-V console (use port 2179, disable negotiation) with VMID
\fIC824F53E\-95D2\-46C6\-9A18\-23A5BB403532\fR
.RE
.PP
\fB+clipboard\fR
.RS 4
Activate clipboard redirection
.RE
.PP
\fB/drive:home,/home/user\fR
.RS 4
Activate drive redirection of
\fI/home/user\fR
as home drive
.RE
.PP
\fB/smartcard:<device>\fR
.RS 4
Activate smartcard redirection for device
\fIdevice\fR
.RE
.PP
\fB/printer:<device>,<driver>\fR
.RS 4
Activate printer redirection for printer
\fIdevice\fR
using driver
\fIdriver\fR
.RE
.PP
\fB/serial:<device>\fR
.RS 4
Activate serial port redirection for port
\fIdevice\fR
.RE
.PP
\fB/parallel:<device>\fR
.RS 4
Activate parallel port redirection for port
\fIdevice\fR
.RE
.PP
\fB/sound:sys:alsa\fR
.RS 4
Activate audio output redirection using device
\fIsys:alsa\fR
.RE
.PP
\fB/microphone:sys:alsa\fR
.RS 4
Activate audio input redirection using device
\fIsys:alsa\fR
.RE
.PP
\fB/multimedia:sys:alsa\fR
.RS 4
Activate multimedia redirection using device
\fIsys:alsa\fR
.RE
.PP
\fB/usb:id,dev:054c:0268\fR
.RS 4
Activate USB device redirection for the device identified by
\fI054c:0268\fR
.RE
.SH "LINKS"
.PP

\m[blue]\fBhttp://www\&.freerdp\&.com/\fR\m[]
.SH "AUTHOR"
.br
.PP
The FreeRDP Team

